### ISSUE TITLE
Need help understanding Equation (4)

### ISSUE THREAD

**Issue by binarydaddy** [JTT94/diffusion_schrodinger_bridge#3]
Hello, thank you for sharing great work.
If possible, could you explain how you derived equation (4)?

Thank you.

**Comment by JTT94** [comment]
This is a very heuristic justification.
 
By Bayes' rule:
$p_{k|k+1}(x_k|x_{k+1}) = p_{k+1|k}(x_{k+1}|x_k) \exp [\log p_k(x_k) - \log p_{k+1}(x_{k+1})]$


For small step size, $\log p_k(x_k) \approx \log p_{k+1}(x_k)$ 
Then by Taylor expansion $\log p_{k+1}(x_k) \approx \log p_{k+1}(x_{k+1}) + \nabla \log p_{k+1}(x_{k+1})(x_k-x_{k+1})$

So $\log p_k(x_k) - \log p_{k+1}(x_{k+1}) \approx \nabla \log p_{k+1}(x_{k+1})(x_k-x_{k+1})$.


$p_{k+1|k}(x_{k+1}|x_k) \propto \exp[-\frac{1}{2} \frac{||x_{k+1}-(x_k+\gamma f(x_k)||^2}{2\gamma}]=\exp[-\frac{1}{2} \frac{|| x_k -(x_{k+1}-\gamma f(x_k))||^2}{2\gamma}]$

Hence, ignoring $x_{k+1}$ terms in constant of proportionality: $p_{k|k+1}(x_k|x_{k+1}) =p_{k+1|k}(x_{k+1}|x_k) \exp [\log p_k(x_k) - \log p_{k+1}(x_{k+1})] \approx \propto \exp[-\frac{1}{2} \frac{|| x_k -(x_{k+1}-\gamma f(x_k))||^2}{2\gamma} + \frac{1}{4 \gamma} 4 \gamma x_k \nabla \log p_{k+1}(x_{k+1})]$ 

$\propto \exp[-\frac{1}{2} \frac{|| x_k -(x_{k+1}-\gamma f(x_k)+2 \gamma \nabla \log p_{k+1}(x_{k+1})||^2}{2\gamma} ]$

Finally $f(x_k) \approx f(x_{k+1})$ for small step size.
