### ISSUE TITLE
Equation in paper

### ISSUE THREAD

**Issue by Gynjn** [JTT94/diffusion_schrodinger_bridge#4]
Thanks for sharing great work.

I have a question on equation in page 3

```math
\nabla \log p_{k+1}\left(x_{k+1}\right)=\mathbb{E}_{p_{0 \mid k+1}}\left[\nabla_{x_{k+1}} \log p_{k+1 \mid 0}\left(x_{k+1} \mid X_0\right)\right]
```

How does it drived..?

Thanks in advance

**Comment by JTT94** [comment]
<img width="553" alt="image" src="https://github.com/JTT94/diffusion_schrodinger_bridge/assets/28487211/1267a77c-ff7b-4de9-9103-d7ee2a46a994">
